version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: roseberry-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roseberry-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/scripts/seed.js && node dist/index.js"

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: roseberry-mobile
    ports:
      - "8081:8081"
    depends_on:
      backend:
        condition: service_started
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0

volumes:
  db_data:


